fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Customer
    from_email:
        address: 'me@example.com'
        sender_name: 'me@example.com'
    registration:
        form:
            type: App\Form\RegistrationType

naviapps_fos_user:
    registration:
        form:
            flow: App\Form\RegistrationFlow
