naviapps_fos_user:
    resource: '@NaviappsFOSUserBundle/Resources/config/routing/all.yml'

naviapps_checkout:
    resource: "@NaviappsCheckoutBundle/Controller/"
    type: annotation

naviapps_cms:
    resource: "@NaviappsCmsBundle/Controller/"
    type: annotation

naviapps_contact:
    resource: "@NaviappsContactBundle/Controller/"
    type: annotation

naviapps_customer:
    resource: "@NaviappsCustomerBundle/Controller/"
    type: annotation

naviapps_sales:
    resource: "@NaviappsSalesBundle/Controller/"
    type: annotation

naviapps_user:
    resource: "@NaviappsUserBundle/Controller/"
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
