# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    AppBundle\Form\ContactFlow:
        parent: craue.form.flow

    AppBundle\Form\RegistrationFlow:
        parent: craue.form.flow
